# Your workflow name.
name: Deploy to Heroku

# Run workflow on every push to the main branch.
on:
  push:
    branches: [master]

# Your workflow jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out your repository.
      - name: Checkout
        uses: actions/checkout@v2

      # Log in to Heroku CLI.
      - name: Log in to Heroku
        run: |
          echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=_ --password-stdin registry.heroku.com

      # Build and push the Docker container.
      - name: Build and push Docker container
        run: |
          docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web .
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      # Release the Docker container to Heroku.
      - name: Release to Heroku
        run: |
          curl -X PATCH https://api.heroku.com/apps/${{ secrets.HEROKU_APP_NAME }}/formation \
            -H "Authorization: Bearer ${{ secrets.HEROKU_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "updates": [
                {
                  "type": "web",
                  "docker_image": "registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web"
                }
              ]
            }'
